### ISSUE TITLE
List of tide stations keyword/ID on search page?

### ISSUE THREAD

**Issue by david-flanders-tuke** [jpr5/webcaltides#12]
For the user to search some example links or a list of known keyword and ID stations.  Especially for international use?

**Comment by PaulJSchellenberg** [comment]
Can you give an example of what you mean? 

Do you mean to have a dropdown from the search bar that shows the relevant stations that match the current value in the search bar?

**Comment by david-flanders-tuke** [comment]
Yes please, or just more examples of typical search queries?

**Comment by jpr5** [comment]
Closing without any further insight as to what to do. 🚫

Please re-open if you have clarification of what's not working, i.e. an example or such. 👍
