### ISSUE TITLE
Only seeing tides through 12/31

### ISSUE THREAD

**Issue by bobcatabbs** [jpr5/webcaltides#22]
How do I see tides for the next calendar year? When I upload the .ics file into Google calendar, I only get tides through December 31, 2023.

**Comment by jpr5** [comment]
Hey there,

The calendar doesn't roll over until Jan 1.  I should modify it to roll forward every month, or maybe every quarter.  Will get to that when I get some time...

Take care,

—Jordan

**Comment by jpr5** [comment]
FYI fixes pending on #25.

**Comment by jpr5** [comment]
Fixed and pushed live.  Enjoy!
